# Wine Quality Dataset
- 와인의 여러가지 특성에 따른 품질등급을 나타낸 데이터
- 11개의 독립변수와 1개의 종속변수(품질등급), 1개의 id로 구성

### 1. 데이터 불러오기

In [38]:
import numpy as np
import pandas as pd
import random
from matplotlib import pyplot as plt
from sklearn import linear_model

df = pd.read_csv('./WineQT.csv')

display(df)
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
0         9.4        5     0  
1         9.8        5     1  
2         9.8        5     2  
3         9.8        6     3  
4         9.4        5     4  
...       ...      ...   ...  
1138     11.0        6  1592  
1139      9.5        6  1593  
1140     10.5        5  1594  
1141     11.2        6  1595  
1142     10.2        5  1597  

[1143 rows x 13 columns]

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000   
mean        8.311111          0.531339     0.268364        2.532152   
std         1.747595          0.179633     0.196686        1.355917   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.392500     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.100000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000   
mean      0.086933            15.615486             45.914698     0.996730   
std       0.047267            10.250486             32.782130     0.001925   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             21.000000     0.995570   
50%       0.079000            13.000000             37.000000     0.996680   
75%       0.090000            21.000000             61.000000     0.997845   
max       0.611000            68.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality           Id  
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000  
mean      3.311015     0.657708    10.442111     5.657043   804.969379  
std       0.156664     0.170399     1.082196     0.805824   463.997116  
min       2.740000     0.330000     8.400000     3.000000     0.000000  
25%       3.205000     0.550000     9.500000     5.000000   411.000000  
50%       3.310000     0.620000    10.200000     6.000000   794.000000  
75%       3.400000     0.730000    11.100000     6.000000  1209.500000  
max       4.010000     2.000000    14.900000     8.000000  1597.000000

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB


### 2. 상관분석

In [40]:
df.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.250728     0.673157   
volatile acidity          -0.250728          1.000000    -0.544187   
citric acid                0.673157         -0.544187     1.000000   
residual sugar             0.171831         -0.005751     0.175815   
chlorides                  0.107889          0.056336     0.245312   
free sulfur dioxide       -0.164831         -0.001962    -0.057589   
total sulfur dioxide      -0.110628          0.077748     0.036871   
density                    0.681501          0.016512     0.375243   
pH                        -0.685163          0.221492    -0.546339   
sulphates                  0.174592         -0.276079     0.331232   
alcohol                   -0.075055         -0.203909     0.106250   
quality                    0.121970         -0.407394     0.240821   
Id                        -0.275826         -0.007892    -0.139011   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.171831   0.107889            -0.164831   
volatile acidity           -0.005751   0.056336            -0.001962   
citric acid                 0.175815   0.245312            -0.057589   
residual sugar              1.000000   0.070863             0.165339   
chlorides                   0.070863   1.000000             0.015280   
free sulfur dioxide         0.165339   0.015280             1.000000   
total sulfur dioxide        0.190790   0.048163             0.661093   
density                     0.380147   0.208901            -0.054150   
pH                         -0.116959  -0.277759             0.072804   
sulphates                   0.017475   0.374784             0.034445   
alcohol                     0.058421  -0.229917            -0.047095   
quality                     0.022002  -0.124085            -0.063260   
Id                         -0.046344  -0.088099             0.095268   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.110628  0.681501 -0.685163   0.174592   
volatile acidity                  0.077748  0.016512  0.221492  -0.276079   
citric acid                       0.036871  0.375243 -0.546339   0.331232   
residual sugar                    0.190790  0.380147 -0.116959   0.017475   
chlorides                         0.048163  0.208901 -0.277759   0.374784   
free sulfur dioxide               0.661093 -0.054150  0.072804   0.034445   
total sulfur dioxide              1.000000  0.050175 -0.059126   0.026894   
density                           0.050175  1.000000 -0.352775   0.143139   
pH                               -0.059126 -0.352775  1.000000  -0.185499   
sulphates                         0.026894  0.143139 -0.185499   1.000000   
alcohol                          -0.188165 -0.494727  0.225322   0.094421   
quality                          -0.183339 -0.175208 -0.052453   0.257710   
Id                               -0.107389 -0.363926  0.132904  -0.103954   

                       alcohol   quality        Id  
fixed acidity        -0.075055  0.121970 -0.275826  
volatile acidity     -0.203909 -0.407394 -0.007892  
citric acid           0.106250  0.240821 -0.139011  
residual sugar        0.058421  0.022002 -0.046344  
chlorides            -0.229917 -0.124085 -0.088099  
free sulfur dioxide  -0.047095 -0.063260  0.095268  
total sulfur dioxide -0.188165 -0.183339 -0.107389  
density              -0.494727 -0.175208 -0.363926  
pH                    0.225322 -0.052453  0.132904  
sulphates             0.094421  0.257710 -0.103954  
alcohol               1.000000  0.484866  0.238087  
quality               0.484866  1.000000  0.069708  
Id                    0.238087  0.069708  1.000000

### 상관분석 결과 0.2이상의 값을 가지는 독립변수 선정해서 모델링 진행

In [41]:
X = df.loc[:,['volatile acidity','citric acid','sulphates','alcohol']]
Y = df.loc[:,'quality']

### 3. 선형회귀 모델링 사용

In [42]:
lr = linear_model.LinearRegression()
lr.fit(X,Y)

LinearRegression()

In [43]:
print("회귀계수", lr.coef_)
print("회귀상수",lr.intercept_)

회귀계수 [-1.2897924  -0.02632209  0.66873952  0.30795161]
회귀상수 2.69392307373369


In [44]:
parmas = np.append(lr.intercept_,lr.coef_)
desighX = np.append(np.ones((len(X),1)),X,axis=1)
predictions = lr.predict(X)
MSE = (sum((Y-predictions)**2))/(len(desighX)-len(desighX[0]))
print(MSE)

0.42189812235630164


In [45]:
var_b = MSE*(np.linalg.inv(np.dot(desighX.T,desighX)).diagonal())
se_b = np.sqrt(var_b)
print(se_b)

[0.23250146 0.13035961 0.11954464 0.12054396 0.01815909]


In [46]:
ts_b = parmas/se_b
print(ts_b)

[11.58669324 -9.89411043 -0.22018632  5.54768162 16.95853927]


In [47]:
from scipy import stats
p_values =[2*(1-stats.t.cdf(np.abs(i),(len(desighX)-len(desighX[0])))) for i in ts_b]
print(p_values)

[0.0, 0.0, 0.8257655395326946, 3.598446385311149e-08, 0.0]


In [48]:
myDF3 = pd.DataFrame()
myDF3["Coefficients"],myDF3["Standard Reeors"],myDF3["t values"],myDF3["p values"] = [parmas,se_b,ts_b,p_values]
print(myDF3)

   Coefficients  Standard Reeors   t values      p values
0      2.693923         0.232501  11.586693  0.000000e+00
1     -1.289792         0.130360  -9.894110  0.000000e+00
2     -0.026322         0.119545  -0.220186  8.257655e-01
3      0.668740         0.120544   5.547682  3.598446e-08
4      0.307952         0.018159  16.958539  0.000000e+00


### 종속변수가 등급을 나타내는 변수여서 모형을 변경해서 진행

## 4. LogisticRegression 모델링
- 데이터셋도 학습과 테스트로 나눠서 진행
- 크기 문제로 등급을 5,6 등급만 별도로 추출해서 데이터 사용

In [8]:
import numpy as np
import pandas as pd
import random
from matplotlib import pyplot as plt
from sklearn import linear_model

df = pd.read_csv('./WineQT.csv')

df1 = df[(df['quality'] >= 5) & (df['quality'] <=6)  ]
data = df1.loc[:,['volatile acidity','citric acid','sulphates','alcohol']]
target = df1['quality']

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data, target, test_size = 0.3, random_state = 42)
display(X_train, X_test, Y_train, Y_test)

volatile acidity  citric acid  sulphates  alcohol
344              0.390         0.40       0.75     10.2
525              0.965         0.10       0.50      9.5
483              0.460         0.31       0.54      9.8
506              1.025         0.43       0.57     10.1
1018             0.180         0.40       0.93     11.3
...                ...          ...        ...      ...
119              0.630         0.07       0.55     10.4
327              0.315         0.54       0.70      9.2
1047             0.690         0.11       0.47      9.7
516              0.720         0.09       0.72     11.1
114              0.600         0.26       0.49      9.4

[661 rows x 4 columns]

volatile acidity  citric acid  sulphates  alcohol
1025             0.590         0.00       0.47     10.3
405              0.600         0.49       0.57     11.4
337              0.240         0.49       1.06     11.0
36               0.500         0.04       0.64      9.4
193              0.545         0.06       0.67     10.7
...                ...          ...        ...      ...
380              0.630         0.24       0.57      9.4
848              0.570         0.21       0.54      9.8
248              0.530         0.79       0.77     13.0
88               1.330         0.00       0.48     10.9
167              0.635         0.37       1.09      9.3

[284 rows x 4 columns]

344     6
525     5
483     5
506     5
1018    5
       ..
119     6
327     6
1047    5
516     6
114     5
Name: quality, Length: 661, dtype: int64

1025    5
405     5
337     6
36      6
193     6
       ..
380     5
848     6
248     5
88      5
167     5
Name: quality, Length: 284, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, Y_train)

LogisticRegression()

In [13]:
from sklearn.metrics import confusion_matrix
print(lr.score(X_train, Y_train))
confusion_matrix(lr.predict(X_train),Y_train)

0.7034795763993948


array([[270, 120],
       [ 76, 195]])

In [14]:
print(lr.score(X_test, Y_test))
confusion_matrix(lr.predict(X_test),Y_test)

0.6795774647887324


array([[101,  55],
       [ 36,  92]])

# 오분류가 생각보다 많이 나와서 새로운 모형을 찾아봐야할듯.